Mobile first
MariamOsman11/-Portfolio- pull request #1
Opened 2023-04-26 12:27 UTC by MariamOsman11

# What I did
-Understand how to parse a Figma design to create a UI.
-Flexbox to place elements in the page.
-Build a personal portfolio site.
-Use images and backgrounds to enhance the look of the website.

2023-04-26 12:32 UTC, BregornOriginal requested changes
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that contains the node_modules folder.

- Kindly add this folder to gitignore 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-26 15:37 UTC, Zuhaib042 reviewed
Hi @MariamOsman11 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has node_modules in repo. kindly have a look at this article on how to delete the node_modules from the remote repo.
https://techstacker.com/remove-node_modules-after-adding-gitignore/
- [ ] Also you dont have linters setup so kindly set up the linters before submitting again

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-27 07:51 UTC, skyv26 requested changes
## Hi @MariamOsman11, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

## Highlights
- Well-structured file and folder structure ✅ 
- Used correctly `Github Flow` ✅ 
- Design looks similar to `Figma` ✅ 
- Well implemented the features ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 07:51 UTC, skyv26 commented on index.html
> +    <section class="hero">
- [ ] Kindly follow the `HTML` semantics properly which will improve your website or portfolio accessibility. As I noticed that you have wrapped your `Header` and `Headline` sections inside the `section` container which is semantically not correct. Please remove this section rest of the structure is fine.

2023-04-27 07:51 UTC, skyv26 commented on index.html
> +    </section>
- [ ] Please also follow the `HTML` semantics properly here which will improve your website or portfolio accessibility. Always wrap the main content inside the `main` tag. Always try to think for the people who can't visualize the website and the `screen` reader will help them to navigate to the `main` section if it is added properly.

2023-04-27 07:51 UTC, skyv26 commented on mit.md
> +## Copyright 2023, [Mariam Osman]
- [ ] Kindly remove the `[` and `]` from your name because it makes your license look unprofessional.

2023-04-27 07:51 UTC, skyv26 commented on mit.md
> +THE [APP TYPE] IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEM
- [ ] Kindly replace your `[APP TYPE]` with relevant information for example name of your website or you can consider `portfolio` instead of `[APP TYPE]`. Because you need to be more specific while issuing a license with the project and it considers good practice in the *IT* world.

2023-04-27 07:51 UTC, skyv26 commented on README.md
> +git
- [ ] Kindly remove this from your `README.md` file because it makes your documentation looks unprofessional. Always see your `README.md` file as a `Project` manual for the user who wants to work on or contribute to your project.

2023-04-27 07:51 UTC, skyv26 commented on README.md
> +This project is [MIT]() licensed.
- [ ] Kindly add the correct path of the MIT `LICENSE` in your project, as I can see you have not added the path correctly.  Please look at the below suggestion to solve your problem.

``` suggestion
This project is [MIT](./mit.md) licensed.
```

2023-04-27 07:51 UTC, skyv26 commented on README.md
> +- Create a new folder to store the files in.
- [ ] Please always put the relevant information which will make your `README.md` file looks more professional. Always consider the `README.md` file as a project manual which will be a time saver for someone.
- [ ] Kindly consider the below example

```
git clone https://github.com/MariamOsman11/-Portfolio-.git
cd -Portfolio-
```

2023-04-27 07:51 UTC, skyv26 commented on README.md
> +- git clone
- [ ] Please always add the relevant information in your `README.md` file because `README.md` is just like a guide for someone who is going to use the project and makes the person understand how your project would work.

### Install Linters

```
cd -Portfolio-
npm i
```

- Above example will help the user to simplify the linter installation process rather put a user into confusion.

2023-04-27 07:51 UTC, skyv26 commented on README.md
> +- I can help in building a product , feature or website Look through some of my work and experience! don’t hestiate to contact me.
- [ ] Please don't add **irrelevant** text inside this section, because this section text should be about how can a user use your repo and run the `project` to see the things in action. Adding irrelevant comments would result in an unprofessional `README.md` file.

2023-04-27 07:51 UTC, skyv26 commented on README.md
> +- You only need a browser to run the html file in.
- [ ] Kindly consider the bullet points to add pre-requisite in a good manner which will help the user to get ready with everything before *dive* directly into `using` your project. Please consider the below example,  but keep remembering to don't just blindly follow the below structure, I would highly suggest you must add the relevant things require before anything.

![Screenshot from 2023-04-25 19-31-28](https://user-images.githubusercontent.com/66476329/234794916-f56ba226-1977-40b6-b329-9440d92b18e8.png)

2023-04-27 09:00 UTC, braincee approved these changes
Hi @MariamOsman11 , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

HIGHLIGHTS
------

 - GitHub flow rightfully used ✅
 - Meaningful title and summary for PR ✅
 - Professional README.md file ✅
 - No linter errors ✅

OPTIONAL CHANGES
---

- [ ] [OPTIONAL] Please I highly recommend capitalizing your commit messages. Example Add... instead of add... 😄 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-27 09:02 UTC, merged