Desktop version
MariamOsman11/-Portfolio- pull request #4
Opened 2023-05-03 14:19 UTC by MariamOsman11

# What I did

- create UIs adaptable to different screen sizes using media queries.
- create a UI from Figma design.
- Use media queries to make sure that your website displays correctly on desktop screens.

2023-05-03 15:07 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @MariamOsman11 :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Professional pull request
✔️ Correct git-flow
✔️ Linter checks are passing

## Required Changes ♻️

- [ ] `Logo` and `Navigation Menu` should be aligned as per the given design. Kindly fix this issue.
***Given design***
![image](https://user-images.githubusercontent.com/60083437/235957779-1bb8bc3d-f2d9-4464-98ef-fe58a741fc41.png)
***Your Design***
![image](https://user-images.githubusercontent.com/60083437/235958001-1ea5eae2-f5f5-47dd-b05f-fe267e02ae61.png)

***Please kindly check the comments below.***

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 15:07 UTC, Tufahel commented on index.html
> +        <!-- <a href="#" class="header-title">My Logo</a> -->
- [ ] Kindly remove unnecessary comments from the codebase to increase readability and cleanliness.

2023-05-04 11:40 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/YPI7uEvEZr7siYRlZD/giphy.gif)

# Hi @MariamOsman11 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Correct use of GitHub Flow ✔
-  UI is looking on point ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 11:40 UTC, AbelG101 commented on README.md
- [ ] [OPTIONAL] Instead of having the live demo link as part of the deployment section I'd advise you to restore the original "Live demo" section and place it there.
  ![image](https://user-images.githubusercontent.com/104968236/236192816-a1be33ee-c5da-45d2-8e17-9da48ded8235.png)
- Here's where you should place it (above the "Getting Started" section):
  ![image](https://user-images.githubusercontent.com/104968236/236193203-3d49ec1a-1db2-4f14-9aa0-6677f97195aa.png)

2023-05-04 12:13 UTC, merged